env:
  browser: true
  es2021: true
extends:
  - plugin:vue/vue3-recommended
  - airbnb-base
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: latest
  parser: '@typescript-eslint/parser'
  sourceType: module
plugins:
  - vue
  - '@typescript-eslint'
  - prettier
rules: 
  import/no-unresolved: off
  import/extensions: off
  no-undef: off
  no-unused-vars: off
  prettier/prettier: off
  vue/max-attributes-per-line: 
    - warn
    - singleline:
        max: 3
