// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    KeyInput: typeof import('./components/atoms/KeyInput/index.vue')['default']
    RemoveConfirm: typeof import('./components/modals/RemoveConfirm/index.vue')['default']
    TextField: typeof import('./components/atoms/TextField/index.vue')['default']
    TextSettings: typeof import('./components/organisms/TextSettings.vue')['default']
    TextTile: typeof import('./components/molecules/TextTile/index.vue')['default']
    TextyInput: typeof import('./components/atoms/TextyInput/index.vue')['default']
  }
}

export { }
