// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/atoms/Button.vue')['default']
    KeyInput: typeof import('./components/atoms/KeyInput.vue')['default']
    ModalProvider: typeof import('./components/templates/ModalProvider.vue')['default']
    RemoveConfirm: typeof import('./components/modals/RemoveConfirm.vue')['default']
    TextField: typeof import('./components/atoms/TextField.vue')['default']
    TextSettings: typeof import('./components/organisms/TextSettings.vue')['default']
    TextTile: typeof import('./components/molecules/TextTile.vue')['default']
    TextyArea: typeof import('./components/atoms/TextyArea.vue')['default']
    TextyInput: typeof import('./components/atoms/TextyInput.vue')['default']
  }
}

export { }
